apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-queue:release1
        name: queue
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: queue
spec:
  ports:
  - port: 8161
    protocol: TCP
  selector:
    app: queue
  type: NodePort
