apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: disk-test1
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod3
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/data1"
          name: myvol2
  volumes:
    - name: myvol2
      persistentVolumeClaim:
        claimName: pvc1
