apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 18Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: testpod4
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/data1"
          name: myvol2
  volumes:
    - name: myvol2
      persistentVolumeClaim:
        claimName: pvc1
